### PR TITLE
Update user_types.md

### PR DESCRIPTION
**Pull request by rlanzafame**
i realized the current user type descriptions are not completely clear and/or a bit out of date. what do you think of these proposed changes?

### CODE REVIEW

**Comment by rlanzafame** [comment]
mude book doesnt have hypothesis anymore so i deleted the example link. if you still want one, maybe it's better for user type 1 to just say "there are several options available" along with a link to the hypothesis and utterances pages in the manual?

**Review by Tom-van-Woudenberg — CHANGES_REQUESTED** [review]
For hypothesis and utterances I think it's better to refer to the page in the manual itself. You can also refer to the local annotator

For user type 3, I feel like the main and release branch doesn't need to be mentioned here. This is certainly not used everywhere.

**Review by Tom-van-Woudenberg — APPROVED** [review]
I made the links relative towards the links in the book
Added new user type images

**Comment by rlanzafame** [comment]
Those images are so cool!!!

**Comment by rlanzafame** [comment]
I'm done with this PR are you?

**Comment by rlanzafame** [comment]
Oh nm I see approval

**Pull request merged**
